# Generated by Django 4.0.4 on 2022-04-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('coral_type', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('lighting', models.CharField(max_length=50)),
                ('water_flow', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=250)),
            ],
        ),
    ]
