# Generated by Django 4.0.4 on 2022-04-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('coral_type', models.CharField(choices=[('S', 'Soft'), ('L', 'Large Polyp Stony'), ('P', 'Small Polyp Stony'), ('A', 'Anemone')], default='S', max_length=1)),
                ('difficulty', models.CharField(choices=[('V', 'Very Sensitive'), ('S', 'Sensitive'), ('M', 'Moderate'), ('H', 'Hardy'), ('A', 'Very Hardy')], default='M', max_length=1)),
                ('lighting', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('V', 'Very High')], default='M', max_length=1)),
                ('water_flow', models.CharField(choices=[('L', 'Low'), ('M', 'Moderate'), ('S', 'Strong')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry', models.CharField(max_length=250)),
                ('coral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coral')),
            ],
        ),
    ]
