# Generated by Django 4.0.4 on 2022-04-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coral',
            name='coral_type',
            field=models.CharField(choices=[('S', 'Soft'), ('L', 'Large Polyp Stony (LPS)'), ('P', 'Small Polyp Stony (SPS)'), ('A', 'Anemone')], default='S', max_length=1),
        ),
    ]
