# Generated by Django 4.0.4 on 2022-04-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_coral_coral_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='coral',
            name='locations',
            field=models.ManyToManyField(to='main_app.location'),
        ),
    ]
